apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suresend.fullname" . }}
  labels:
    {{- include "suresend.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.secrets.jwtSecret | quote }}
  DATABASE_URL: {{ .Values.api.secrets.databaseUrl | quote }}
  REDIS_URL: {{ .Values.api.secrets.redisUrl | quote }}
  STRIPE_SECRET_KEY: {{ .Values.api.secrets.stripeSecretKey | quote }}
